gb_web/models.py
from flask_login import UserMixin
from .app import db


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))

# class Article(db.Model):
#     __tablename__ = "articles"
#
#     id = db.Column(db.Integer, primary_key=True)
#     title = db.Column(db.String(255))
#     text = db.Column(db.Text())
#     author = None

gb_web/app.py
from os import getenv, path

from flask import Flask
from json import load

from .extension import db, login_manager
from .article.views import article
from .models import User
from .user.views import user
from .index.views import index
from .report.views import report
from .auth.view import auth

CONFIG_PATH = getenv("CONFIG_PATH", path.join("../dev_config.json"))

VIEWS = [
    index,
    user,
    article,
    report,
    auth
]


def create_app() -> Flask:
    app = Flask(__name__)
    app.config.from_file(CONFIG_PATH, load)
    register_extensions(app)
    register_blueprints(app)
    return app


def register_extensions(app):
    db.init_app(app)

    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


def register_blueprints(app: Flask):
    for view in VIEWS:
        app.register_blueprint(view)

gb_web/article/views.py
from flask import Blueprint, render_template
from flask_login import login_required
from werkzeug.exceptions import NotFound

from ..user.views import get_user_name

article = Blueprint("article", __name__, url_prefix="/article", static_folder="../static")

ARTICLES = {
    1: {
        "title": "Time for time",
        "text": "many texts",
        "author": 2
    },
    2: {
        "title": "Time for relax",
        "text": "more texts",
        "author": 2
    },
    3: {
        "title": "Cry In floor",
        "text": "not many texts",
        "author": 1
    },
    4: {
        "title": "Crying floor",
        "text": "fantasy is end",
        "author": 3
    }
}


@article.route("/")
@login_required
def article_list():
    return render_template(
        "articles/list.html",
        articles=ARTICLES
    )


@article.route("/<int:pk>")
@login_required
def get_article(pk: int):
    if pk in ARTICLES:
        article_raw = ARTICLES[pk]
    else:
        raise NotFound("Article id:{}, not found".format(pk))
    title = article_raw["title"]
    text = article_raw["text"]
    author = get_user_name(article_raw["author"])
    return render_template(
        "articles/details.html",
        title=title,
        text=text,
        author=author
    )

gb_web/index/views.py
from flask import Blueprint, render_template

index = Blueprint("index", __name__, url_prefix="/", static_folder="../static")


@index.route("/")
def main_page():
    return render_template(
        "base.html"
    )

gb_web/report/views.py
from flask import Blueprint, render_template

report = Blueprint("report", __name__, url_prefix="/reports", static_folder="../static")


@report.route("/")
def report_list():
    return render_template(
        "base.html",
        reports=[1,231,4]
    )

gb_web/user/views.py
from flask import Blueprint, render_template
from flask_login import login_required
from werkzeug.exceptions import NotFound

user = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")
USERS = {
    1: {"name": "Ivan"},
    2: {"name": "Jon"},
    3: {"name": "Mary"}
}


@user.route("/")
@login_required
def user_list():
    from ..models import User
    users = User.query.all()
    return render_template(
        "users/list.html",
        users=users
    )


@user.route("/<int:pk>")
@login_required
def profile(pk: int):
    from ..models import User
    _user = User.query.filter_by(id=pk).one_or_none()
    if _user is None:
        raise NotFound("User id:{}, not found".format(pk))
    return render_template(
        "users/details.html",
        user=_user
    )


def get_user_name(pk: int):
    if pk in USERS:
        user_name = USERS[pk]["name"]
    else:
        raise NotFound("User id:{}, not found".format(pk))
    return user_name

gb_web/templates/articles/details.html
{% extends "base.html" %}

{% block title %}
    Article details
{% endblock %}
{% block body %}
    <h1>
        {{ title }}
    </h1>
    <br>
    {{ text }}
    <br>
    {{ author }}
{% endblock %}

gb_web/templates/articles/list.html
{% extends "base.html" %}

{% block title %}
    Users list
{% endblock %}
{% block body %}
    {% for article_id in articles %}
        <ul>
            <a href="{{ url_for('article.get_article', pk=article_id) }}">{{ articles[article_id]["title"] }}</a>
        </ul>
    {% endfor %}
{% endblock %}

gb_web/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% include "navbar.html" %}
      {% block css %}
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
  </head>
  <body>
    {% block body %}{% endblock %}
    {% block js %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"  ></script>
    {% endblock %}
  </body>
</html>

gb_web/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('index.main_page') }}">GB Flask</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('index.main_page') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('user.user_list') }}">Users</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('article.article_list') }}">Articles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('report.report_list') }}">Reports</a>
          </li>
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('auth.login') }}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

gb_web/templates/reports/reportslist.html
{% extends "base.html" %}

{% block title %}
    Reports list
{% endblock %}
{% block body %}
    {% for report in reports %}
        <ul>
            <li>
                {{ report }}
            </li>
        </ul>
    {% endfor %}
{% endblock %}

gb_web/templates/users/details.html
{% extends "base.html" %}

{% block title %}
    Users details
{% endblock %}
{% block body %}
    <h1>
        {{ user.email }}
    </h1>
{% endblock %}

gb_web/templates/users/list.html
{% extends "base.html" %}

{% block title %}
    Users list
{% endblock %}
{% block body %}
    {% for user in users %}
        <ul>
            <a href="{{ url_for('user.profile', pk=user.id) }}">{{ user.email }}</a>
        </ul>
    {% endfor %}
{% endblock %}